### ISSUE TITLE
IBInspectable

### ISSUE THREAD

**Issue by hhanesand** [ArtSabintsev/UIFloatLabelTextField#10]
Maybe think about adding the `IBInspectable` macro to properties for those that want to use IB to customize the control?

**Comment by ArtSabintsev** [comment]
Not a bad idea - will do it soon!

**Comment by ArtSabintsev** [comment]
So, a bit busy at the moment - I'll get to it next weekend, unless you get to it sooner via a Pull Request =p

**Comment by lightice11** [comment]
Maybe :)

**Comment by ArtSabintsev** [comment]
I haven't forgotten about this thing. I just haven't had time :\ - hoping to get to it soon.

**Comment by ArtSabintsev** [comment]
I finally got to this issue. Apparently, it's not possible to have a property marked with both `IBDesignable` **and** `UI_APPEARANCE_SELECTOR`. Therefore, I had to make a choice, and I chose to stick with `UI_APPEARANCE_SELECTOR`.

http://matthewmorey.com/interface-builder-or-uiappearance/
