### ISSUE TITLE
Floating Label Padding

### ISSUE THREAD

**Issue by TiagoVeloso** [ArtSabintsev/UIFloatLabelTextField#11]
Hi,

I need to add some padding to the floating label.

I've noticed you have a property for that in the private interface.

Would it be possible to put that in the public class interface?

**Comment by ArtSabintsev** [comment]
You're referring to the horizontal padding, correct? If so, I can easily expose that for you :)

Just reply back to confirm and I'll do it shortly thereafter.

**Comment by TiagoVeloso** [comment]
Yes. Its the horizontal padding property.

**Comment by ArtSabintsev** [comment]
Done and pushed to Cocoapods as version 1.2.1.

**Comment by TiagoVeloso** [comment]
Thank you very much sir :)

**Comment by ArtSabintsev** [comment]
You're very welcome!

**Comment by TiagoVeloso** [comment]
I can confirm it's working

**Comment by ArtSabintsev** [comment]
Even better :)
