### ISSUE TITLE
Animate when the textfield gains focus

### ISSUE THREAD

**Issue by TiagoVeloso** [ArtSabintsev/UIFloatLabelTextField#12]
Hi, I was wondering, it is possible to get the floating label to animate when the user focuses the textfield?

**Comment by ArtSabintsev** [comment]
It's possible to do that, I just haven't had the time to implement that little feature. I'll put it on my TO-DO list.

**Comment by TiagoVeloso** [comment]
If i manage the time I'll try to do it myself and then make a pull request.

**Comment by ArtSabintsev** [comment]
Sounds good!

**Comment by TiagoVeloso** [comment]
Just posted a PR for this: #13

**Comment by ArtSabintsev** [comment]
Thanks, I'll take a look tonight. Closing this issue for now.
