### ISSUE TITLE
Failed to load designables from path (null)

### ISSUE THREAD

**Issue by Reedyuk** [ArtSabintsev/UIFloatLabelTextField#14]
"error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)"
I'm getting this error when using the pod version of the library, I have the object in a tableview in a storyboard, but i assumed this should be fine.
![screen shot 2015-06-18 at 10 20 42](https://cloud.githubusercontent.com/assets/3853006/8228049/bde6629a-15a3-11e5-8e5c-cd111cf65346.png)

**Comment by ArtSabintsev** [comment]
Hi,

Is the first error from mine, and the second error from the other pod, JVFloatLabelTextView? The fact you're getting an error with both repositories is problematic, but may be telling as well. 

Can you make a sample story board project, and try integrating it there. Does the problem persist?

**Comment by Reedyuk** [comment]
Ah you are correct, its related to the JVFloatLabeledTextField, sorry.

**Comment by ArtSabintsev** [comment]
You may want to try using UIFloatLabelTextField or UIFloatLabelTextView.
Both use the appearance proxy over IBDesignable, as those two aspects are mutually exclusive.

**Comment by Reedyuk** [comment]
It turns out that this was an issue with cocoapods!
https://github.com/CocoaPods/CocoaPods/issues/2792
you need to add use_frameworks! to your podfile and it will be fine.

**Comment by ArtSabintsev** [comment]
Gotcha - thanks for the update!
