### ISSUE TITLE
animateClearingTextFieldWithArray

### ISSUE THREAD

**Issue by Kaspik** [ArtSabintsev/UIFloatLabelTextField#18]
Hi!

I have problem with `clear button`. In method `animateClearingTextFieldWithArray` there is 
```objc
[[UIApplication sharedApplication] endIgnoringInteractionEvents];
```
 but only for `else`. When if condition is true, application is not "responding" for any touches.

**Comment by ArtSabintsev** [comment]
I think PR #17 is related to this issue. I'll look at it today as I have time.

**Comment by Kaspik** [comment]
This PR is for little bit different behavior, but maybe it can fix this too. My opinion for this fix is moving
```objc
[[UIApplication sharedApplication] endIgnoringInteractionEvents];
```
before/after `if` condition.

**Comment by ArtSabintsev** [comment]
sure - makes sense - will do that.

**Comment by ArtSabintsev** [comment]
hmm, you know what, never mind - this is expected behavior. I want to ignore touches when the animation plays out purposefully, as to not allow the addition of extra text or anything that could screw up the animation

**Comment by ArtSabintsev** [comment]
Closing for now.

**Comment by ArtSabintsev** [comment]
I accepted that PR a moment ago. Doubtful it will help, but you can try shortly. Going to cut a release now and update the Pod.

**Comment by Kaspik** [comment]
Well, right, you want ignore touches while cleaning but after that it should enable touch sgain - in other case the app is not responding for anything.

Will try after new pod update.

**Comment by ArtSabintsev** [comment]
pod should be updated

**Comment by ArtSabintsev** [comment]
keep me posted
