### ISSUE TITLE
Getting error "this class is not key value coding-compliant" when launch my app on iOS 7.1.2.

### ISSUE THREAD

**Issue by andrew-buksha** [ArtSabintsev/UIFloatLabelTextField#21]
Hello.
I'm using this library for my app. And when I launched it on iOS 7.1.2 I got an error saying "*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIFloatLabelTextField 0x17ec9720> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key borderActiveColor".
borderActiveColor could change to placeholderColor or borderInactiveColor as well.
It works OK on iOS 8 and higher.
What the problem could be?

**Comment by ArtSabintsev** [comment]
hmm - there is no borderActiveColor in UIFloatLabelTextField. Are you sure it's this library?

**Comment by andrew-buksha** [comment]
On one of my screen I have UITextField subclassed as UIFloatLabelTextField and in User Defined Attributes I specify following attributes:
placeholderColor
borderActiveColor
borderInactiveColor

Like so:
![2016-04-15 15 54 31](https://cloud.githubusercontent.com/assets/15215481/14561921/66a2cfd8-0322-11e6-8039-a49d4acb07b5.png)

And running the app on iOS 7 ends up throwing an error that I mentioned.

**Comment by ArtSabintsev** [comment]
Like I said, there are no attributes with those names in the library. I'm not sure why you're using them.

Also, I don't even know if this library supports iOS 7 anymore. I've moved everything to at least iOS 8+, but at this point I don't believe it's even worth supporting anything but iOS 9, as iOS 9 has 80%+ of the marketshare.

**Comment by andrew-buksha** [comment]
OK, I got you. I just don't understand why it's working fine on 8+ but not on 7.
Anyway, I think I just change minimum deployment to 8.0 if its working OK.
Thank you.

**Comment by ArtSabintsev** [comment]
ok good - happy to hear it!
