### ISSUE TITLE
Carthage produces framework without headers

### ISSUE THREAD

**Issue by grillbiff** [ArtSabintsev/UIFloatLabelTextField#22]
Hi, 

when I try to build UIFloatLabelTextField with Carthage it produces a framework with no headers.

Not sure if there is another way I'm supposed to import UIFloatLabelTextField when using Carthage?

**Comment by ArtSabintsev** [comment]
Will take a look in the next 48 hours.

I'm a cocoapods and have only done minimal testing win Carthage.

**Comment by grillbiff** [comment]
👍  using the pod now instead so no hurry on my part :)

**Comment by ArtSabintsev** [comment]
Ok happy to hear that.

**Comment by ArtSabintsev** [comment]
And sorry for the atrocious grammar in the previous message - was on mobile and dead tired.

**Comment by ArtSabintsev** [comment]
Try now. I forgot to tag the latest commit which had the sample project schemes marked as *shared schemes*.

**Comment by grillbiff** [comment]
:thumbsup: great! will try it tonight. Thanks for the speedy fix

**Comment by ArtSabintsev** [comment]
My pleasure - keep me posted.
