### ISSUE TITLE
How to change Clear button color

### ISSUE THREAD

**Issue by srinadh588** [ArtSabintsev/UIFloatLabelTextField#23]
Hi, It works good. i though need a small animation looks good as well as how to change clear button color to our own.

**Comment by ArtSabintsev** [comment]
Hey - just saw this issue! Sorry it took so long.

I need to expose `_clearTextFieldButton` in the interface to achieve that. I'll look into doing that along side PR #26

**Comment by srinadhK** [comment]
@ArtSabintsev  Hi, thanks for reply. Can you please give an option to change clear button color as well. So it would be helpful for me a lot.

**Comment by ArtSabintsev** [comment]
That option will be automatically exposed when I expose the button itself.

**Comment by ArtSabintsev** [comment]
This is now available in version 1.2.7.

**Comment by srinadhK** [comment]
@ArtSabintsev  Cool.
