### ISSUE TITLE
How to adjust the vertical space?

### ISSUE THREAD

**Issue by yuzhongxingke** [ArtSabintsev/UIFloatLabelTextField#24]
thanks!

**Comment by ArtSabintsev** [comment]
You can't through an exposed API, however, if you manipulate the code on these two lines (https://github.com/ArtSabintsev/UIFloatLabelTextField/blob/master/UIFloatLabelTextField/UIFloatLabelTextField.m#L258-L259), you can do it.

Closing this issue. Feel free to re-open if you have more questions.

**Comment by yuzhongxingke** [comment]
OK! thank you!
