### ISSUE TITLE
Using UIFloatLabelTextField with xib file

### ISSUE THREAD

**Issue by Atayuksel** [ArtSabintsev/UIFloatLabelTextField#27]
Hi,

I tried to use UIFloatLabelTextField in xib file. However, xcode did not update the cell and it remained as a standart UITextField. When I initialize the cell with        
cell = [[NSBundle mainBundle] loadNibNamed:@"ABCTableViewCell" owner:self options:nil][0];
but it remains as a UITextField. 
What should I do to make it visible and usable with xib file.

**Comment by ArtSabintsev** [comment]
Did you change the UITextField to UIFloatLabelTextField in the inspector in IB?

**Comment by ArtSabintsev** [comment]
Closing this issue as there's been no response. Feel free to comment on here with any follow up information and I'll happily re-open the issue.

**Comment by diego1199** [comment]
I've change in the inspector the class to UIFloatLabelTextField but still get the same UITextField

Thanks

**Comment by ArtSabintsev** [comment]
Can you provide a sample project?
