### ISSUE TITLE
the field is resigning when touch in clear (x) button

### ISSUE THREAD

**Issue by orafaelreis** [ArtSabintsev/UIFloatLabelTextField#8]
dear,

when user touch at (x) clear button inside textfield the field is resigning and the keyboard hide at this moment. This is not the default behavior to UITextField.

May I doing something wrong?

**Comment by ArtSabintsev** [comment]
This is expected behavior. Would you like to be able to turn off the auto-dismissal?

**Comment by ArtSabintsev** [comment]
Alright, I decided to change the behavior. 

From the release notes of v1.1.1:

- By default, the keyboard no longer disappears when pressing the clear-text button.
- Before v1.1.1, the keyboard would disappear.
- A new variable was introduced to toggle the state of the keyboard after pressing the clear-text button.
