### ISSUE TITLE
Initializing 'UIButton *(*)(__strong id, SEL)' with an expression of type 'void *' converts between void pointer and function pointer`

### ISSUE THREAD

**Issue by Tchelow** [ArtSabintsev/UIFloatLabelTextField#9]
After install `UIFloatLabelTextField`, I am receiving an error for the line:
`UIButton * (* clearButtonFunctionPointer)(id, SEL) = (void *)clearButtonImplementation;`

The error is:
`UIFloatLabelTextField.m:111:19: Initializing 'UIButton *(*)(__strong id, SEL)' with an expression of type 'void *' converts between void pointer and function pointer`

Supported iOS versions are 7 and 8 and target is iPhone.

**Comment by ArtSabintsev** [comment]
Hey @Tchelow,

Does the sample app work for you? The sample app has a deployment target of iOS 7.1, and compiles for me. Also, the app compiles on a deployment target of 8.1 and 8.2 as well. 

Also, what version of Xcode are you using? I just tested it on on Xcode 6.1.1 and 6.2 beta, and it works on both.

Can you try importing the project into a fresh/new app and see if you get the issue?

**Comment by Tchelow** [comment]
Thanks for your reply.
The sample works fine. It's just happening if I import it in this specific project, but I don't have any idea why. I can disable the clear button by now, but don't know if it'll be necessary in the future... If you have any suggestion, it would be great.

**Comment by ArtSabintsev** [comment]
Hey @Tchelow,

Well, if the sample project works, that means the code works 

With that being said, I can't do much without seeing your project/code. 

Let's start here: what version of Xcode are you using, and what versions of iOS are you targeting?

**Comment by Tchelow** [comment]
Yeah... I know... but thanks for the help anyway. :)
I'm using Xcode 6.1.1.
Target is iOS 7.0

**Comment by ArtSabintsev** [comment]
Hmm, no clue my friend. If you want to send me your project, feel free to send it arthur@sabintsev.com and I can take a look when I have some time. Otherwise, I'm closing this issue for now.

**Comment by Tchelow** [comment]
Hey @ArtSabintsev, here is what I found to solve my issue
`UIButton * (* clearButtonFunctionPointer)(id, SEL) = (UIButton *(*)(id, SEL))clearButtonImplementation;`

**Comment by ArtSabintsev** [comment]
Woah! Ya, that works! Good job! I'll implement the fix right away. Nice job, man!

**Comment by ArtSabintsev** [comment]
ok, pushed it to master and cocoapods. Gave you credit in the README.

Thanks for the change!

**Comment by Tchelow** [comment]
:+1: Thanks! :)

**Comment by ArtSabintsev** [comment]
Thanks - appreciate your help!

**Comment by LukeDurrant** [comment]
FYI if you have warning pedantic then this is what will cause the issue

**Comment by ArtSabintsev** [comment]
@LukeDurrant are you saying the fix throws the warning, the code before the fix?

**Comment by LukeDurrant** [comment]
No no the fix works I'm just saying the reason that it wasn't happening in the sample project is because the complier flag wasn't set on that project and was in @Tchelow

**Comment by ArtSabintsev** [comment]
Ah, got it! Thanks for clearing that up, @LukeDurrant!
